//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PaperPlanner_Application.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AnswersTable
    {
        public int AnswerId { get; set; }
        public int UserID { get; set; }
        public int PaperID { get; set; }
        public int QuesID { get; set; }
        public string CorrectAns { get; set; }
        public string AttemptedAns { get; set; }
        public Nullable<System.DateTime> AttemptDate { get; set; }
    
        public virtual QuestionPaper QuestionPaper { get; set; }
        public virtual Question Question { get; set; }
        public virtual User User { get; set; }
    }
}
