//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PaperPlanner_Application.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;

    public partial class ApprovedQuestionPaper
    {
        [Key]
        public int approveID { get; set; }

        [Required]
        [DisplayName("Approver ID")]
        public int approverID { get; set; }

        [Required]
        [DisplayName("Approver Name")]
        public string approverName { get; set; }

        [Required]
        [DisplayName("Question Paper ID")]
        public int approvedPaperID { get; set; }

        [Required]
        [DisplayName("Approval Date")]
        public System.DateTime approvalDate { get; set; }

        [Required]
        [DisplayName("Approval Status")]
        public string approveStatus { get; set; }

        public virtual User User { get; set; }
        public virtual QuestionPaper QuestionPaper { get; set; }
    }
}
