//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PaperPlanner_Application.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;

    public partial class QuestionPaper
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public QuestionPaper()
        {
            this.Questions = new HashSet<Question>();
            this.ApprovedQuestionPapers = new HashSet<ApprovedQuestionPaper>();
            this.AnswersTables = new HashSet<AnswersTable>();
            this.QuesPaper_Attempted_By_Users = new HashSet<QuesPaper_Attempted_By_Users>();
        }

        [Key]
        public int quesPaperID { get; set; }

        [Required]
        [DisplayName("Question Title")]
        public string qpTitle { get; set; }

        [Required]
        public int qpCreatorID { get; set; }

        [Required]
        [DisplayName("Question Description")]
        public string qpDescription { get; set; }

        [DisplayName("Creation Date")]
        public System.DateTime qpCreatedDate { get; set; }

        [DisplayName("Status")]
        public string qpStatus { get; set; }

        [DisplayName("Sent Approval Date")]
        public Nullable<System.DateTime> qpApprovalSendDate { get; set; }

        [DisplayName("Approved Date")]
        public Nullable<System.DateTime> qpApprovedDate { get; set; }

        [DisplayName("Rejected Date")]
        public Nullable<System.DateTime> qpRejectedDate { get; set; }

        [DisplayName("Updated Date")]
        public Nullable<System.DateTime> qpUpdatedDate { get; set; }

        public virtual User User { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Question> Questions { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ApprovedQuestionPaper> ApprovedQuestionPapers { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AnswersTable> AnswersTables { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<QuesPaper_Attempted_By_Users> QuesPaper_Attempted_By_Users { get; set; }
    }
}
