//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PaperPlanner_Application.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;

    public partial class Question
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Question()
        {
            this.AnswersTables = new HashSet<AnswersTable>();
        }

        [Key]
        public int quesId { get; set; }

        [Required]
        [DisplayName("Question")]
        public string quesText { get; set; }

        [Required]
        [DisplayName("Question Options (Separated by Commas)")]
        public string quesOptions { get; set; }

        [Required]
        [DisplayName("Correct Option")]
        public string quesAnswer { get; set; }

        [Required]
        [DisplayName("Question Paper ID")]
        public int quesPaperID { get; set; }

        [DisplayName("Question Updated Date")]
        public Nullable<System.DateTime> quesUpdatedDate { get; set; }

        [DisplayName("Question Created Date")]
        public Nullable<System.DateTime> quesCreationDate { get; set; }

        public virtual QuestionPaper QuestionPaper { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AnswersTable> AnswersTables { get; set; }
    }
}
