//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PaperPlanner_Application.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;

    public partial class QuesPaper_Attempted_By_Users
    {

        [DisplayName("Attempted ID")]
        public int AttemptID { get; set; }

        [DisplayName("User ID")]
        public int UserID { get; set; }

        [DisplayName("Paper ID")]
        public int PaperID { get; set; }

        [DisplayName("Attempted Date")]
        public Nullable<System.DateTime> Attemptedon { get; set; }

        [DisplayName("Total Questions")]
        public int TotalQuestions { get; set; }

        [DisplayName("Correct Questions")]
        public int CorrectQuestions { get; set; }

        [DisplayName("Unattempted Questions")]
        public int UnattemptedQuestions { get; set; }

        [DisplayName("Incorrected Questions")]
        public int IncorrectQuestions { get; set; }

        public virtual QuestionPaper QuestionPaper { get; set; }
        public virtual User User { get; set; }
    }
}
