//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PaperPlanner_Application.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;

    public partial class User
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public User()
        {
            this.QuestionPapers = new HashSet<QuestionPaper>();
            this.ApprovedQuestionPapers = new HashSet<ApprovedQuestionPaper>();
            this.AnswersTables = new HashSet<AnswersTable>();
            this.QuesPaper_Attempted_By_Users = new HashSet<QuesPaper_Attempted_By_Users>();
        }

        [Key]
        public int userID { get; set; }

        [Required(ErrorMessage = "Username is Required")]
        [DisplayName("Your Username")]
        public string username { get; set; }

        [Required(ErrorMessage = "Password is Required")]
        [DisplayName("Your Password")]
        [DataType(DataType.Password)]
        public string password_hash { get; set; }

        [Required(ErrorMessage = "Email is Required")]
        [RegularExpression(@"^[a-zA-Z0-9._%+-]+@[a-zA-Z0-9.-]+\.[a-zA-Z]{2,}$", ErrorMessage = "Invalid email format")]
        [DisplayName("Your Email Address")]
        public string email { get; set; }

        [Required(ErrorMessage = "Role is Required")]
        [DisplayName("Your Role")]
        public string role { get; set; }

        [Required(ErrorMessage = "Full Name is Required")]
        [DisplayName("Your Full Name")]
        public string fullname { get; set; }

        [Required(ErrorMessage = "Age is Required")]
        [DisplayName("Your Age")]
        public int age { get; set; }

        [Required(ErrorMessage = "Gender is Required")]
        [DisplayName("Your Gender")]
        public string gender { get; set; }

        [DisplayName("User Updated Date")]
        public Nullable<System.DateTime> updatedDate { get; set; }

        [DisplayName("User Created Date")]
        public Nullable<System.DateTime> createdDate { get; set; }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<QuestionPaper> QuestionPapers { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ApprovedQuestionPaper> ApprovedQuestionPapers { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AnswersTable> AnswersTables { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<QuesPaper_Attempted_By_Users> QuesPaper_Attempted_By_Users { get; set; }
    }
}
